### ISSUE TITLE
Error running merali: 'ActionBatchAppliance' object has no attribute '__name__'

### ISSUE THREAD

**Issue by fitchtravis** [PackeTsar/meraki-cli#3] opened 2021-03-27 13:24 UTC
After installing meraki-cli using; 

python3 -m pip install meraki-cli

I get this error running 'meraki;

AttributeError: 'ActionBatchAppliance' object has no attribute '__name__'

pip list | grep meraki
meraki              1.7.1
meraki-cli          1.2.0

**Comment by PackeTsar** [comment] 2021-03-27 14:32
Yep I can reproduce this. Looks like Meraki made some changes to their library that broke it. For a quick fix, you can run `python3 -m pip install meraki==1.6.2`.

I will get a repaired version out today.

**Comment by fitchtravis** [comment] 2021-03-28 12:48
Hey, can confirm dropping back to meraki==1.6.2 works.

**Comment by PackeTsar** [comment] 2021-03-28 12:51
Still working on the fix. Meraki's SDK changed their structure a bit and I'm having to rewrite how I interpret it into an argument parser. Having to go from a simple flat interpreter into a recursive one.

**Comment by PackeTsar** [comment] 2021-04-04 16:42
This has been fixed in v1.3.0 which has just been released. Use `pip3 install --upgrade --no-cache-dir meraki-cli` or `python3 -m pip install --upgrade --no-cache-dir meraki-cli` to upgrade to it and fix the problem.

**Closed** 2021-04-04 16:42 UTC
